name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Use node@14
      uses: actions/setup-node@v1
      with: { node-version: '14.x' }

    - name: Node modules cache
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: |
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
          ~/.cache/node-gyp-cache
        key: "${{ runner.os }}-yarn-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}"
        restore-keys: |
          ${{ runner.os }}-yarn-${{ env.cache-name }}-
      env:
        cache-name: v4

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Check build
      run: yarn build

    - name: Check linting
      run: yarn lint:check
